FROM eclipse-temurin:23-jdk as builder


WORKDIR /app

COPY . .



RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:23-jre

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar


EXPOSE 8080


ENTRYPOINT ["java", "-jar", "app.jar"]
